# Generated by Django 4.2.6 on 2023-10-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.CharField(max_length=999, primary_key=True, serialize=False)),
                ('name_course', models.CharField(max_length=255)),
                ('img_course', models.ImageField(blank=True, upload_to='assets/img/post/%Y/%m/%d/')),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(max_length=10)),
                ('pl_course', models.CharField(max_length=255)),
                ('objects_course', models.CharField(max_length=255)),
                ('target', models.TextField(max_length=5000)),
                ('gv', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
    ]
