# Generated by Django 4.2.6 on 2023-10-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_img_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_course',
            field=models.ImageField(blank=True, upload_to='course/%Y/%m/%d/'),
        ),
    ]
