# Generated by Django 4.2.6 on 2023-10-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_gv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_course',
            field=models.ImageField(upload_to='course/%Y/%m/%d/'),
        ),
    ]
